### ISSUE TITLE
Create NPM module

### ISSUE THREAD

**Issue by LuXDAmore** [pqina/flip#2]
I've seen the `other Issue from React`, but i prefer to use it as an `npm-module` directly inside a component and not globally, it's possible?

**Comment by LuXDAmore** [comment]
And thank you for the amazing work! 🚀 

It's the missing plugin for counters!

😄

**Comment by rikschennink** [comment]
There's no npm module yet, so, I guess creating one would be the starting point.

I might get to it next week.

**Comment by LuXDAmore** [comment]
Oook, thank you very much dude ✌️

**Comment by Raghav-Kumar-Jha** [comment]
First of all, Thanks for your work so far. **I strongly agree that Creating an `npm module ` for this counter file is required so much so that we can use it in React projects.**
**### Kindly create the `npm Module` as soon as you can.** 
I am waiting. Thanks again.

**Comment by rikschennink** [comment]
@LuXDAmore this should now work

```
npm i @pqina/flip --save
```

```js
import Tick from '@pqina/flip';

console.log(Tick);
// logs {supported: true, options: {…}, helper: {…}, data: {…}, DOM: {…}, …}
```

**Comment by LuXDAmore** [comment]
Oooh thank you very much!! 🚀

**Comment by Raghav-Kumar-Jha** [comment]
Thanks for making the npm module. But I am still unable to use it in my react application. Can you please post me an example that How can I use this npm in my react functional component to display a timer? Please give an example to use it.  Thanks again.

**Comment by rikschennink** [comment]
See https://github.com/pqina/flip/issues/1
